- docker-compose.yml
- updates the docker compose file to be specific to atla-hyku container registry
> changes to docker compose

- app/actors/hyrax/actors/paper_or_report_actor.rb
- app/controllers/catalog_controller.rb
- app/controllers/hyrax/paper_or_reports_controller.rb
- app/forms/hyrax/paper_or_report_form.rb
- app/indexers/paper_or_report_indexer.rb
- app/models/paper_or_report.rb
- app/models/solr_document.rb
- app/presenters/hyrax/paper_or_report_presenter.rb
- app/views/hyrax/base/_attribute_rows.html.erb
- app/views/hyrax/paper_or_reports/_paper_or_report.html.erb
- app/views/records/edit_fields/_date_created.html.erb
- app/views/records/edit_fields/_license.html.erb
- config/initializers/hyrax.rb
- config/locales/blacklight.en.yml
- config/locales/paper_or_report.de.yml
- config/locales/paper_or_report.en.yml
- config/locales/paper_or_report.es.yml
- config/locales/paper_or_report.fr.yml
- config/locales/paper_or_report.it.yml
- config/locales/paper_or_report.pt-BR.yml
- config/locales/paper_or_report.zh.yml
- spec/actors/hyrax/actors/paper_or_report_actor_spec.rb
- spec/controllers/hyrax/paper_or_reports_controller_spec.rb
- spec/factories/paper_or_reports.rb
- spec/features/create_paper_or_report_spec.rb
- spec/forms/hyrax/paper_or_report_form_spec.rb
- spec/models/paper_or_report_spec.rb
- spec/presenters/hyrax/paper_or_report_presenter_spec.rb
Refs #24 
There is not Paper or Report worktype
There is a Paper or Report worktype
Show page:
<details>
</details>
Search page:
<details>
</details>
- This PR does not include controlled vocab fields
- This PR does not make Title a single value field (part of GenericWork pr)
- Translations will need to be generated
> Create PaperOrReport worktype

- app/indexers/app_indexer.rb
Subject field should be capitalized, & trailing spaces & periods should be removed
- #28 
- subjects would be saved however they were entered in the work form.
- subjects will be saved with a capital letter, and period / trailing spaces will be stripped.
<details>
<summary>what i entered in the subject field</summary>
</details>
<details>
<summary>what is saved in the data for subject_tesim</summary>
</details>
<details>
<summary>what is saved in the data for subject_sim</summary>
</details>
> Normalize subjects

- config/initializers/hyrax.rb
Don't require files upon work creation. 
- #66
> Dont require files

- app/views/records/edit_fields/_format.html.erb
- config/authorities/formats.yml
- forgot to add one commit to last PR
#72
> 2 more format changes

- app/indexers/app_indexer.rb
- app/models/etd.rb
- lib/oai/provider/metadata_format/hyku_dublin_core.rb
adds work_url to the oai feed for the oai_hyku prefix
> added work_url to oai_hyku output

- ops/production-deploy.tmpl.yaml
- ops/staging-deploy.tmpl.yaml
Update ingress ir.atla.com
Add client dns to replace s3 provided dns to ingress
> Update ingress ir.atla.com

- ops/production-deploy.tmpl.yaml
Set fcrepoBasePathOverride since deafult is atla-hyku-production and not /hykuprod as we wanted
> investigate-tenant-creation-error

- config/authorities/resource_types.yml
We have legacy data to upload into a tenant. Many of the works are missing resource type so I am adding "Unknown" to be used for these works.
<details>
</details>
> added value "Unknown" to resource type list

- config/authorities/institutions.yml
Updated Atla to Atla RIM in controlled vocab Institutions
<details>
</details>
> updated Atla to Atla RIM in inst. list

- app/controllers/catalog_controller.rb
- app/forms/hyrax/etd_form.rb
- app/models/etd.rb
- app/models/solr_document.rb
- app/presenters/hyrax/etd_presenter.rb
- app/views/hyrax/base/_attribute_rows.html.erb
- config/initializers/bulkrax.rb
- config/locales/etd.de.yml
- config/locales/etd.en.yml
- config/locales/etd.es.yml
- config/locales/etd.fr.yml
- config/locales/etd.it.yml
- config/locales/etd.pt-.yml
- config/locales/etd.pt-BR.yml
- config/locales/etd.zh.yml
- config/locales/hyrax.de.yml
- config/locales/hyrax.en.yml
- config/locales/hyrax.es.yml
- config/locales/hyrax.fr.yml
- config/locales/hyrax.it.yml
- config/locales/hyrax.pt-.yml
- config/locales/hyrax.pt-BR.yml
- config/locales/hyrax.zh.yml
- lib/oai/provider/metadata_format/hyku_dublin_core.rb
- lib/oai/provider/model_decorator.rb
- spec/factories/etds.rb
- spec/features/create_etd_spec.rb
- spec/forms/hyrax/etd_form_spec.rb
- spec/models/etd_spec.rb
We decided that the field level on the ETD work type was not clear and probably duplicating degree so I removed it. I looked for every file that referred to level and either remove or commented it out. I then tested creating an ETD work and importing an ETD work and everything appears to be working.
<details>
</details>
> removed level from etd

- app/assets/stylesheets/atla-overrides.scss
- app/views/hyrax/collections/show.html.erb
> changed collection show page and added related css

- app/assets/stylesheets/themes/cultural_show.scss
- app/controllers/application_controller.rb
- app/views/themes/cultural_show/hyrax/base/show.html.erb
- app/views/themes/scholarly_show/hyrax/base/show.html.erb
- config/tinymce.yml
Fixed the work show themes so they match the wireframes in the UI and added citations to them all bcz they were missing. Added tinymce functionality for text blocks, change our private tenant login 
Refs #issuenumber(
<details>
</details>
> Fixes07 27

- app/assets/stylesheets/atla-overrides.scss
> added css for embargo/lease settings ui

- app/assets/stylesheets/atla-overrides.scss
> fixed css for icon used to remove facets

- Gemfile
- Gemfile.lock
> Change bulkrax branch to main

- app/controllers/application_controller.rb
> ssl fix for atla

- config/authorities/licenses.yml
- config/authorities/rights_statements.yml
Made all URLs in the rights and creative commons https
<details>
</details>
> updated licenses and rights to https

- config/authorities/institutions.yml
- config/tinymce.yml
> fixed library name and added to tinymce

- app/views/shared/_appearance_styles.html.erb
Fixed footer link color hover, primary button background color and active tab background color so that the color you choose in the UI changes in the page.
<details>
</details>
> fixed ui color picker

- .github/workflows/brakeman-audit.yaml
- .github/workflows/bundler-audit.yaml
Push button bundler and brakeman audit through github actions for end of month client reporting
Having to manually bring each repository locally and run the commands
Push button bundler and brakeman audit through github actions
> add-brakeman-and-bundler-audit-ghas

- app/models/etd.rb
- app/models/generic_work.rb
- app/models/image.rb
- app/models/paper_or_report.rb
PDFs shall not be split!
Related to:
- https://github.com/scientist-softserv/atla-hyku/issues/188
> ♻️ Remove IIIF Print splitting

- app/forms/hyrax/image_form.rb
This commit will remove "Abstract" from required fields and add "Host Insitution" to required fields.
> 🧹 Move Image form fields

- app/views/shared/_footer.html.erb
Fixed the order of the footer links  to match the ones higher up in the page
<details>
</details>
> made footer links match top links order

- app/helpers/blacklight/blacklight_helper_behavior.rb
- config/locales/etd.de.yml
- config/locales/etd.en.yml
- config/locales/etd.es.yml
- config/locales/etd.fr.yml
- config/locales/etd.it.yml
- config/locales/etd.pt-.yml
- config/locales/etd.pt-BR.yml
- config/locales/etd.zh.yml
added text to help text for title, subjects and keywords on ETD work form
<details>
</details>
> updated help text on etd form

- ops/staging-deploy.tmpl.yaml
Add deploy to r2-atla-dl cluster for atla-hyku-staging env
Waiting to hear back form client that the ir-staging domain is targetted to teh cname in our notch8.cloud that is targetting to the clusters loadbalancer.
Need t0 persist changes currently on staging for ir-staging.atla.com ingress
> add-hyku-staging-env-r2-atla-dl
