.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Refs https://github.com/scientist-softserv/dev-ops/issues/630
Hyku projects come with their own issue and PR templates from base Hyku. This PR updates these templates for the versions we've developed at SoftServ.
=> updates base hyku templates to use softserv versions

README.md, Repo_README.md, app/assets/stylesheets/viewer.scss, app/forms/hyrax/generic_work_form.rb, app/models/generic_work.rb, app/models/solr_document.rb, app/presenters/hyku/work_show_presenter.rb, app/views/hyrax/base/_form.html.erb, app/views/hyrax/base/_video_embed_viewer.html.erb, app/views/hyrax/base/show.html.erb, app/views/layouts/hyrax/dashboard.html.erb, app/views/themes/cultural_show/hyrax/base/show.html.erb, app/views/themes/scholarly_show/hyrax/base/show.html.erb, config/initializers/bulkrax.rb, config/locales/hyrax.en.yml, db/schema.rb
SoftServ will customize the ability for YouTube videos to appear embedded on a work show page. Videos will not be played back in Universal Viewer.
- #9 
- all works that should show a UV show them
- users would only see either the uv viewer or default image
- If a work has a valid `video_embed` link saved in its metadata, the work show page will show that video in an iframe.
- If a work does not have a valid `video_embed` link saved in its metadata, but should show the universal viewer because it has files, it shows the viewer.
- If a work does not have either `video_embed` metadata or files to show in the viewer, it shows the default image. 
<details>
<summary>Working youtube player</summary>
</details>
<details>
<summary>Working vimeo player</summary>
</details>
<details>
<summary>Form …
=> embedded iframe for videos

app/controllers/concerns/hyrax/works_controller_behavior.rb
Error messages from validations in the edit-work form were appearing as blank- the message was not being parsed correctly. This PR updates the works controller behavior to make sure that these error messages are being set.
- https://github.com/scientist-softserv/atla-hyku/issues/45
- #9 
- users would see a blank error message
- users will not see a blank error message at the top of the screen
<details>
<summary>Working error message for :video_embed</summary>
</details>
Potential contribute back to hyku
=> Fix error message formatting for edit work form

lib/oai/provider/metadata_format/hyku_dublin_core.rb, lib/oai/provider/model_decorator.rb
Refs #10 
Adds mappings for new metadata added to ETD and Paper or Report worktypes
OAI Hyku feed was missing new custom metadata fields
OAI Hyku feed will have all metadata in the feed
<details>
</details>
=> update mappings for OAI Hyku

app/indexers/etd_indexer.rb, app/indexers/paper_or_report_indexer.rb
- the subject field was not parsing correctly for Etds because the corresponding generated indexer was not inheriting from the app_indexer.
- all worktype indexers should inherit from the app_indexer so that there is a way to add indexing methods in just one place that can apply across all worktypes
- #52 
- subject field was not parsing correctly for Etd works
- subject field parses correctly for Etd works (the first letter will be capitalized, and any spaces or periods on the end will be stripped)
<details>
<summary>Etd with a subject</summary>
</details>
=> Fix inheritance of indexers

config/locales/etd.en.yml, config/locales/hyrax.en.yml, config/locales/paper_or_report.en.yml
- rights statement help text should be a link
- removes properties in the other worktype's yaml that are repeated - they inherit from the value in `en.yaml` so they are not necessary
=> Cleanup yml, add link in rightsstatement

app/indexers/app_indexer.rb, app/services/hyrax/format_service.rb, app/views/records/edit_fields/_format.html.erb, config/authorities/formats.yml
- format was not being saved correctly. The service was missing a few methods that were in the DL in order to make this happen
- extra non-blank fields were being added in the work form. now the field includes a blank option so that it doesn't just save extra pdf formats
- alphabetizes the formats in the dropdown
- removes duplicate MPEG & OGG, adds MOV
- #27 
<details>
<summary>format showing up correctly for imported work </summary>
</details>
<details>
<summary>new list of formats</summary>
</details>
=> Format rework

app/models/etd.rb, app/views/records/edit_fields/_year.html.erb, config/authorities/types.yml, config/locales/etd.en.yml
- makes date just use a validation that it is a 4 digit number beginning with 19 or 20 instead of a dropdown
- removes Still Image from Types
- updates the year help text to be more clear what years it is expecting
- #29 
- #48 
<details>
<summary>year field on etds</summary>
</details>
=> Date + Type rework

app/views/hyrax/base/_attribute_rows.html.erb
- links to search on work show page for date created, identifier, and year were broken
- make date created and identifier actually search with their links
- https://github.com/scientist-softserv/atla-hyku/issues/24
- could not search from the links on the work show page for date created, identifier, and year
- can not search from the links on the work show page for date created, identifier, and year
https://share.getcloudapp.com/P8u2J2QP
=> make date created and identifier actually search with their links

Gemfile.lock, app/models/etd.rb, app/models/paper_or_report.rb
@kirkkwang 
- PDFs were not splitting correctly, which was causing them to not show up in the viewer for both Paper or Report & Etd worktypes.
- the generated derivative files need to be created as generic worktypes instead of as `self`
- #69 
- pdfs would not show up in the viewer for paper or report & etd worktypes
- pdfs display in the viewer for paper or report & etd worktypes
- derivative files are created for each pdf page for paper or report & etd worktypes
<details>
<summary>successful etd work with pdf</summary>
</details>
=> Pdf files not showing in viewer

app/models/concerns/bulkrax/has_local_processing.rb, config/initializers/bulkrax.rb
Based on client feedback
- https://github.com/scientist-softserv/atla-hyku/issues/27#issuecomment-1553691046
- https://github.com/scientist-softserv/atla-hyku/issues/27
You could import csvs that listed id of the format controlled vocab (for instance, application/pdf)
You can add any alt for formats in csv imports (see list here https://github.com/scientist-softserv/atla-hyku/blob/main/config/authorities/formats.yml)
<details>
<summary>Error thrown with wrong type of format</summary>
</details>
=> Make format validate correctly

app/presenters/hyku/work_show_presenter.rb
CSV imports have an array with an empty string when there is a blank value in the cell. The method that determines wheter the embedded video or the uv displays needs to account for that on the show pages. 
- #88
=> Fix array with empty string bug

config/locales/etd.en.yml
The help text for department should only be set for etds - not for the user accounts
Refs #90
=> department help text should only apply to etds

app/models/solr_document.rb
dc:type maps to work type as the default in hyku for `oai_dc`. I do not think this needs to be the case.
In the oai gem, [it says that the field_semantics hash is used to assign the values for the `oai_dc` feed](https://github.com/projectblacklight/blacklight_oai_provider/blob/69795b06cc37150386b6d9732be027d200412598/README.md?plain=1#L107)
I checked in both [Hyrax](https://github.com/search?q=repo%3Asamvera%2Fhyrax%20field_semantics&type=code) & [Blacklight](https://github.com/search?q=repo%3Aprojectblacklight%2Fblacklight%20field_semantics&type=code), and this `field_semantics` hash doesn't seem to be used anywhere else that is not related to the blacklight oai gem. I also saw that the `field_semantics` hash was added to the `solr_document.rb` just 4 years ago, [in a commit by rob to …
=> Remap dc type so it points to types in the oai_dc feed

app/models/user.rb, config/routes.rb, docker-compose.yml
=> Tenant to see sidekiq

app/models/concerns/bulkrax/has_local_processing.rb, app/models/user.rb, config/routes.rb, docker-compose.yml
#130 
Any model with out a year was throwing an error
Only throw an error on the year if the year is required
Asking Christi this question:
- We validate the format and year fields. If the field is required on a work type and it does not match the format we through an error. What do we do if it is not required? Do we make it blank or do we still throw an error on that records import?
=> Use model for required fields

app/assets/stylesheets/atla-overrides.scss, app/assets/stylesheets/themes/shared_repository.scss
=> added css to hide host inst field from all but the shared theme

app/controllers/hyrax/contact_form_controller.rb
compared to the hyrax & hyku contact form, code in `contact_form_controller`, some seemingly crucial methods were missing that was causing the form to display an error page. namely, the `:build_contact_form` method and before action. This should also fix the negative captcha issue
- https://github.com/scientist-softserv/atla-hyku/issues/19
https://share.getcloudapp.com/KouEPjEx
- contact form page did not load
- contact form page loads
- user is able to submit the form without errors. 
(unable to test on mailtrap, but it works locally)
=> Fix broken contact form and negative captcha

config/locales/devise_invitable.de.yml, config/locales/devise_invitable.en.yml, config/locales/devise_invitable.es.yml, config/locales/devise_invitable.fr.yml, config/locales/devise_invitable.it.yml, config/locales/devise_invitable.pt-.yml, config/locales/devise_invitable.pt-BR.yml, config/locales/devise_invitable.zh.yml
When a new user receives an email to activate their account, the email has a `<br />`
tag in it. We have received a lot of reports of these emails going to spam and this could be a contributing factor.
Changes proposed in this pull request:
removes the `<br />` tag from the email text in each of the locale files
User email has an html tag in the text
User email does not have html tags in the text
=> remove html tag from invite user email locales

app/controllers/hyku/invitations_controller.rb, spec/controllers/hyku/invitations_controller_spec.rb
Ref 
- https://github.com/scientist-softserv/palni-palci/issues/813 
- https://github.com/samvera/hyku/pull/2025 (`cherry-pick` source) 
- https://github.com/scientist-softserv/palni-palci/pull/856 
Trying to add a user active in other repositories to another tenant does not return any error but does not add the user. 
Changes proposed in this pull request:
* Always add invited users to the tenant's Registered Users group 
1. Login as a super admin 
2. Create a new tenant (e.g. `Tenant A`)
3. Navigate to `Tenant A` > Dashboard > Manage Users 
4. Invite a new user who does not already exist in the **application** (i.e. across all tenants, not just one) 
5. Verify that the new user gets added to the Registered Users group in `Tenant A` 
6. Create a new tenant (e.g. `Tenant B`) 
7. Navigate …
=> Inviting existing users fails

app/views/records/edit_fields/_default.html.erb
2f88bc3faa864dc560832573a7886dba5ba05db5
This commit will hide the PDF form fields on the descriptions tab.  The
fields are still on the files tab but as checkboxes.
The new PDF form fields show up on the descriptions tab.
The new PDF form fields are hidden on the descriptions tab.
=> 🐛 Hide PDF form fields on descriptions tab

app/forms/hyrax/pdf_form_behavior.rb
This commit will fix the unpermitted params error that occurs when trying to save the form.  It seemed that shoveling the terms in broke functionality for other terms.  Instead we override the class method and add it to the array of terms.
=> 🐛 Fix unpermitted params

app/views/catalog/_index_gallery_collection_wrapper.html.erb, app/views/catalog/_thumbnail_list_collection.html.erb
This commit will remove a Hyrax override that seemed to be causing some issues with the search list view and also bring in a fix from PALs with to address the search gallery view.
Ref:
- https://github.com/scientist-softserv/atla-hyku/issues/122
- https://github.com/scientist-softserv/palni-palci/pull/540
Custom thumbnails were not showing up in list and gallery search views.
Custom thumbnails now show up correctly.
List view:
Gallery view:
=> 🐛 Fix custom thumbnail showing on searches

Dockerfile
This commit is required to resolve the issue with uploading images from the Collections' branding tab. Because the symlink wasn't established, a user would not be able to see the images they uploaded even though the path correctly exists.
Issue:
- https://github.com/scientist-softserv/atla-hyku/issues/119
BEFORE: 
AFTER:
=> 🐛 [i119] - add symlink to public/branding

app/forms/hyrax/image_form.rb, app/models/image.rb, app/presenters/hyrax/image_presenter.rb, app/views/hyrax/base/_attribute_rows.html.erb, config/locales/hyrax.en.yml
This commit will add new properties to the Images work type. The new properties are:
additional_rights_info
institution
resource_type
types
format
video_embed
Ref:
- https://github.com/scientist-softserv/atla-hyku/issues/145
Image work type was just had the default metadata
Image work type has customized metadata
<details>
<summary>Form</summary>
</details>
<details>
<summary>Record</summary>
</details>
=> 🎁 Add new properties to Images work type

app/controllers/catalog_controller.rb, app/forms/hyrax/etd_form.rb, app/forms/hyrax/generic_work_form.rb, app/forms/hyrax/image_form.rb, app/forms/hyrax/paper_or_report_form.rb, app/models/etd.rb, app/models/generic_work.rb, app/models/image.rb, app/models/paper_or_report.rb, app/models/solr_document.rb, app/presenters/hyrax/etd_presenter.rb, app/presenters/hyrax/generic_work_presenter.rb, app/presenters/hyrax/image_presenter.rb, app/presenters/hyrax/paper_or_report_presenter.rb, app/views/hyrax/base/_attribute_rows.html.erb, config/locales/hyrax.en.yml, spec/forms/hyrax/etd_form_spec.rb, spec/forms/hyrax/generic_work_form_spec.rb, spec/forms/hyrax/image_form_spec.rb, spec/forms/hyrax/paper_or_report_form_spec.rb, spec/models/etd_spec.rb, spec/models/generic_work_spec.rb, spec/models/image_spec.rb, spec/models/paper_or_report_spec.rb, spec/support/shared_examples_for_generic_work_form.rb
This commit will add the `location` property to all work types and adjusts all the forms, models, and presenters to support it.  The `CatalogController` was also updated to support the new property as well as the `SolrDocument` and locale yml.
Ref:
- https://github.com/scientist-softserv/atla-hyku/issues/148
=> 🎁 Add location property to all work types

app/models/image.rb
This commit removes the `abstract` validation on the Image model which should not be a required field.
=> 🐛 Remove abstract requirement on Image

app/models/ability.rb, app/services/roles_service.rb, app/views/hyrax/dashboard/sidebar/_repository_content.html.erb, config/locales/en.yml, db/schema.rb, spec/factories/etds.rb, spec/factories/generic_works.rb, spec/factories/group.rb, spec/factories/images.rb, spec/factories/roles.rb, spec/features/manage_user_groups_and_roles_spec.rb
Introduces an Advanced Depositors group with Work Importer role.
Addresses previously failing ability specs.
Refs 
- #123 
- https://github.com/scientist-softserv/atla-hyku/issues/183
Importers and exporters are open to everyone
Only Admin user and those in the Advanced Depositor group will have access to importers and exporters
<details>
<summary>Screenshots</summary>
</details>
- Requires rake task to load roles and groups: `rake hyku:roles:create_default_roles_and_groups`
- Adds new translations to en.yml file only. Requires running a translation service to add other language translations.
=> Introduces importer permission restrictions

app/controllers/hyrax/my/works_controller_decorator.rb
Prior to this commit, when you were on page 2 of your works and selected a work to add to a collection, the query for available collections would use the page 2 as part of the collection query. This would mean the first 100 collections (default page size) that you had access to add works to were skipped.
With this commit, we omit the query parameters from the works page and then query collections.
Refs #194 
When selecting works from page 1 and using `Add to Collection`, user was able to select a collection.
For subsequent pages of works, no collection was found.
`Add to Collection` button works on all pages of works.
<details>
</details>
=> 🐛 Fix "Add to Collection" for page 2+ of works

app/controllers/bulkrax/exporters_controller_decorator.rb, app/controllers/bulkrax/importers_controller_decorator.rb
Refs
- https://github.com/scientist-softserv/atla-hyku/issues/123
Prior work limited the ability to view the importer and exporter pages by user role, but did not limit what importers and exporters could be seen.
With this work, only admin users can see all importers and exporters, while other users can only see importers and exporters they have created.
Users with advanced depositor role can see all importers and exporters.
Only admin can see all importers and exporters. Advanced depositors can only see what they have created.
<details>
</details>
=> Limit importers and exporters by user

Gemfile.lock, app/helpers/iiif_print_helper.rb, app/models/concerns/pdf_behavior.rb, app/presenters/hyku/work_show_presenter.rb, app/services/iiif_print/tenant_config.rb, config/application.rb, db/migrate/20231128191136_add_model_details_to_iiif_print_pending_relationships.iiif_print.rb, db/schema.rb, docker-compose.bundle.yml, spec/presenters/concerns/hyrax/iiif_av/displays_content_decorator_spec.rb, spec/presenters/hyku/work_show_presenter_spec.rb, spec/services/iiif_print/tenant_config_spec.rb
This is a preliminary commit to add conditional logic for either
rendering PDF.js or IIIF viewer for split pages.
There is a particular case where QA might appear to fail:
1. Set the Tenant to use UV
2. Create a work with a PDF (this will split the page)
3. Go to the work's page, you'll see the UV
4. Set the Tenant to use PDF.js
5. Refresh the work page, and you should see PDF.js but instead will see
the UV.
To work around this (and realistically how most people will experience this):
1. Set the Tenant to use UV
2. Create a work with a PDF
3. Go to the Dashboard
4. Click the work's URL
5. You should see a UV for the PDF
6. Close the work's page
7. Change the tenant to use PDF.js
8. Go to the Dashboard
9. Click the work's URL
The conjecture is that there's some iframe and/or turbolinks …
=> 🎁   Add conditional PDF split or PDF.js

config/features.rb
spltting has been corrected to splitting in the feature flipper description for :default_pdf_viewer.
Refs
- https://assaydepot.slack.com/archives/C031E2NF43T/p1701706582689099
[Staging](https://demo.atla-hyku.notch8.cloud/admin/features?locale=en)
Local
=> 🧹 Correct spltting typo

.env, app/controllers/admin/users_controller.rb, app/views/hyrax/admin/users/index.html.erb, config/locales/de.yml, config/locales/devise_invitable.de.yml, config/locales/devise_invitable.es.yml, config/locales/devise_invitable.fr.yml, config/locales/devise_invitable.it.yml, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/it.yml, config/locales/pt-.yml, config/locales/pt-BR.yml, config/locales/simple_form.de.yml, config/locales/simple_form.en.yml, config/locales/simple_form.es.yml, config/locales/simple_form.fr.yml, config/locales/simple_form.it.yml, config/locales/simple_form.pt-.yml, config/locales/simple_form.pt-BR.yml, config/locales/simple_form.zh.yml, config/locales/zh.yml, config/routes.rb, ops/production-deploy.tmpl.yaml, ops/staging-deploy.tmpl.yaml, spec/controllers/admin/users_controller_spec.rb
I added the work to make an activate user button. Also made some text changes.
<details>
</details>
=> Added activate users button 

.github/workflows/brakeman-audit.yaml, .github/workflows/build-base.yaml, .github/workflows/build-solr.yaml, .github/workflows/build-test-lint.yaml, .github/workflows/bundler-audit.yaml, .github/workflows/deploy.yaml
Refs
- #171 
v0.0.15 includes the `SMTP_USER_NAME` variable, which should fix an issue where emails are not sending. 
The `SMTP_USER_NAME` variable is not included in the Deploy action. 
The `SMTP_USER_NAME` variable is included in the Deploy action.
=> update actions version to v0.0.15

app/helpers/blacklight/blacklight_helper_behavior.rb
I'm seeing the following in Sentry:
```
ArgumentError
wrong number of arguments (given 1, expected 2)
```
With this commit, we factor towards the correct arity while also allowing additional parameters.
=> 🐛 Address `ActionView::Template::Error`

app/controllers/catalog_controller.rb, app/forms/hyrax/etd_form.rb, app/models/etd.rb, app/models/paper_or_report.rb
For the ETD work form i moved creative commons down to the additional fields. Added faceting to the work type model for the fields it was missing from to fix the error that was happening when you clicked on a value for those fields.
<details>
</details>
=> Ck updates2024 04
